name: step types

on:
  workflow_dispatch: # manually triggering workflow

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello from Bash"

  say-hello-inline-go:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Go
        run: sudo apt-get update && sudo apt-get install -y golang-go

      - name: Run Inline Go
        run: |
          cat <<EOF > hello.go
          package main
          import "fmt"
          func main() { fmt.Println("Hello from Go") }
          EOF

          go run hello.go

  say-hello-javascript-action:
    runs-on: ubuntu-24.04
    steps:
      - name: Use JavaScript GitHub Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "World"
